name = "tadoku"
main = "src/index.js"
compatibility_date = "2024-12-01"
workers_dev = true
routes = [
  { pattern = "tadoku.lurraca.com", custom_domain = true }
]

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "tadoku-stories"

[[kv_namespaces]]
binding = "KV"
id = "b0659592313941b1887fc030cf9b461f"
